### PR TITLE
Clean up README install instructions a little bit.

### PR DESCRIPTION
**Pull request by ondrae**
Hey, I tried installing your project and ran into a few issues. This PR fixes those and adds the steps I needed to take to the README.

The main change was it appears you've changed your database name at some point during development. I change the relevant makefile to refer to the new db name. I has to add the hstore extension manually as well. If it get installed elsewhere, take out that line from the instructions.

You should also add something about needing a local .env file for foreman to work as well.

I don't know anything about gulp, and it took a while to get working on my machine. But when it did! Whew your screener looks great!

### CODE REVIEW

**Comment by ondrae** [comment]
Oops, I also had to manually run `psql screener_test -c "CREATE EXTENSION hstore;"` to get the tests to work locally.

**Comment by mapsam** [comment]
Hey! Thanks for taking the time to go through the install! The README was in major need of updates. I'll let @esmithayer or @bengolder speak for some of the DB related issues, but I'm wondering which `gulp` issues you ran into? Did it not install properly with `npm install`?

**Comment by esmithayer** [comment]
Hey Andrew, thanks for going through this! I think the database name issue is just that the example DATABASE_URL in the readme has "screener" as the database name instead of "rva-screening"--it's probably easier for us to change that than the makefile since I think we're all using databases called rva-screening at this point, but really we should just make the makefile use the environment variable.

**Comment by mapsam** [comment]
@esmithayer want to merge this in when you think it's ready?

**Comment by mapsam** [comment]
:+1:

**Pull request merged**
