### PR TITLE
New css from prototypes

### PR DESCRIPTION
**Pull request by mapsam**
The following commit is an aggregate of all changes currently at http://github.com/codeforamerica/rva-screening-ui-prototypes in order to prepare for our upcoming trip to RVA.

Major changes include:
- custom CSS (removed bootstrap)
- updated search/create patient workflow, now "Search First" (located at `index.html`)
- functionality for filter patients has been combined with search into `index.html`. Filters are going to be statistical aggregates of patients, such as (_**3_\* patients have been shared with your clinic today*) > clicking that button will show you which patients.
- JS now broken into unique files for simpler editing, also exposed globally as major constructors
- main navigation is mobile "swipe" friendly (but needs some major work and testing)

TODO before this should be merged:
- [x] re-introduce bootstrap `forms.css` so we can still have nice looking forms on the patient details page
- [x] update `.container` in some pages that are currently missing
- [x] re-add prescreening styles from old `_base.scss` file. (merged in #182)
- [x] style login page
- [ ] ~~make "View Patients" filters more mobile friendly - probably turn into a dropdown menu instead of buttons on mobile~~ not doing this purely for the sake of time, will address in next round!

### CODE REVIEW

**Comment by mapsam** [comment]
@esmithayer I added the styles back from the original site for the prescreener, but I'm not able to run `python add_screening_criteria_data.py` successfully, so I can't really see any changes. Let me know if you're able to take a look!

Very likely that it won't look great :stuck_out_tongue_closed_eyes:

**Comment by esmithayer** [comment]
Oh yeah, that needs the new create_app configuration. One sec.

**Comment by esmithayer** [comment]
Fixed in #182.

**Comment by mapsam** [comment]
Boom! :boom:

**Comment by mapsam** [comment]
I've added back the styles for the prescreener and results. Also included a new sidebar navigation (breadcrumb style) just as an experiment.

rva-screener-prescreenernewcss

You can also use the sidebar breadcrumbs as a way to progress the prescreener app:

rva-screener-prescreenernewcss2

I've also added styles for `.errors` per @esmithayer's addition in #178

screen shot 2015-07-26 at 10 30 06 pm

**Pull request merged**
