### PR TITLE
Form structure cleaning

### PR DESCRIPTION
**Pull request by mapsam**
This does three major things:
1. makes fields in patient details cleaner, simpler, and more malleable to be moved around
2. styles all security forms (i.e. password change, login, etc) and uses the `login.html` template instead of `base.html` to avoid unnecessary scripts from loading
3. restyles many-to-one fields to be a bit more concise, taking up less space

screen shot 2015-09-28 at 12 37 31 pm
screen shot 2015-09-28 at 12 37 36 pm
screen shot 2015-09-28 at 12 38 08 pm
screen shot 2015-09-28 at 12 38 22 pm

### CODE REVIEW

**Comment by mapsam** [comment]
@esmithayer should the `relogin.html` template be moved into the `security/` directory?

**Comment by mapsam** [comment]
OH no :anguished:

**Comment by esmithayer** [comment]
Haha yeah, it's not part of Flask-Security so it doesn't need to be in the security folder.

**Comment by mapsam** [comment]
Yay, I fixed a test and it worked!

**Pull request merged**
