### PR TITLE
Add translations for our current prescreening templates

### PR DESCRIPTION
**Pull request by bengolder**
- [x] new_prescreening.html
- [x] prescreening_basic.html
- [x] prescreening_results.html

### CODE REVIEW

**Comment by bengolder** [comment]
spanish

**Comment by bengolder** [comment]
I've added a ton more translations. Most of the app is translated.
espanol

**Comment by bengolder** [comment]
### The current state of translation

The large majority of of the app is translated but it is not completely translated (see Remaining pieces below). I've translated all the portions of all the templates that I thought reasonable to do at this stage. As with the English version, the Spanish version will need ongoing copyediting to ensure clarity and correctness. Many of the terms are domain-specific, so it would be best to review them with a person who has experience using Spanish within safety net health services. The Spanish version is likely to have more copy errors than the English version at this stage.

The Spanish version is deployed at https://demo-screener-es.herokuapp.com/

There is currently no link or mechanism to switch the language, so the URL must be accessed directly.

### Remaining pieces

These are the portions of the app that remain untranslated and we may wish to translate.
1. Repetitive hardcoded examples in html (View Edit History, for example)
2. CSS ("new patient", "recently updated" on index.html page)
3. Hardcoded Service descriptions and service information in the database (Share Patient, Prescreening Results)
4. Non-choice description fields in the database (address type, document type, phone number type)

**Comment by mapsam** [comment]
Huzzah! :+1:

**Pull request merged**
