### PR TITLE
Adding Access Now Fields

### PR DESCRIPTION
**Pull request by bengolder**
- added translation wrappers for edit history strings in models.py
- added residency fields
- changed full_name to first, last, middle
- using "q_an" class on access now specific fields

### CODE REVIEW

**Comment by mapsam** [comment]
Excellent!

I assume there will be a number of questions that have multiple clinics' classes on the `form-field`?

**Comment by bengolder** [comment]
TODO (not in this branch, but would be good for #183): 
- [ ] add questions to javascript for conditional display
- [ ] add classes & change HTML to address new CSS changes
- [ ] adjust the width of various fields, particularly year & month inputs.

@mapsam I'm going to avoid that for now and just have it match the current general state of the html. We can address that in a separate branch. `q_an` is being attached at the `form-group` level of the current HTML, which sort of matches `form-field`.

**Comment by bengolder** [comment]
This can be merged into `master`

You will need to run `make db_update` to perform a migration and upgrade, because this branch adds several fields to the database.

**Comment by mapsam** [comment]
Oops, I'm getting my classes mixed up. Just wondering if we'll have groups of questions that are used for multiple services, essentially leading to a class structure of `form-group q_an q_dp` ?

**Comment by bengolder** [comment]
Adding classes to everything looked too tricky, so I currently only added it to service-specific ones on Access Now. Daily Planet's Qs unique Qs are not yet included and have no class.
But yes: `form-group q_an`

**Comment by mapsam** [comment]
Sounds good. Just wondering if it will every happen in the future since it will dictate how the filtering scripts run.

:+1: to merging this!

**Pull request merged**
