### PR TITLE
Profiles

### PR DESCRIPTION
**Pull request by mapsam**
### What changed?
- new route & template for user profiles, #134 
- new route & template for service profiles, #135 
- temporary `SERVICE_DATA` in `views.py` to work with templates

### CODE REVIEW

**Comment by mapsam** [comment]
rva-screener-serviceprofiles

**Comment by esmithayer** [comment]
There's a backend instead of example data now!

A couple other things we could add to this page:
-Eligibility criteria, especially all the sliding scales in one place, since the prescreener just shows you the scale you fall under.
-How to start the application process (someone mentioned this in user testing).
-Something about the types of care each service offers? Not sure if it makes more sense to associate this with services or service locations.

**Comment by esmithayer** [comment]
Right now, users can get to service profiles via the prescreener, and potentially links in patient details or on the "search new patients" page, right? It seems like we might eventually want a page that just lets you browse all of the services that are part of the application.

**Comment by mapsam** [comment]
Boom :boom: nice work!

Talked with @bengolder a bit about this page yesterday as well.  There is a lot of information we can put on these pages, but in order to figure out _where_ it all goes we should confirm during his user tests next week _what_ information would be priority for users on these pages.

Any thoughts on how user profiles should look? There really isn't a lot of information for a users right now, which makes the page a bit sparse.

**Comment by mapsam** [comment]
Going to merge this in to keep us moving along - but not considering #134 or #135 closed!

**Pull request merged**
