### PR TITLE
patient_overview.html addition, #21

### PR DESCRIPTION
**Pull request by mapsam**
### What Changed?
- adding `patient_overview.html` template, relates to #21 
- nav updates
- css changes related to the above

### CODE REVIEW

**Comment by svmatthews** [comment]
rva-patient-overview

**Comment by svmatthews** [comment]
MOAR ART!

**Comment by mapsam** [comment]
Here's a screencast:

rva-patient-overview

**Comment by bengolder** [comment]
We might want to rename this template to "browse_patients.html" to avoid confusion with the single patient overview.

**Comment by mapsam** [comment]
This change is actually the final page in the gif - with the single patient details/documents/etc.

The "browse patient" page is the [`view_login-success.html`](https://github.com/codeforamerica/rva-screening/blob/template-prototypes/view_login-success.html), which isn't a very good name but it includes multiple features so "browse" didn't seem to make sense - but that can be updated as well to something like `landing.html` ?

**Comment by mapsam** [comment]
Closing this in favor of @bengolder's implementation in #37

**Pull request closed without merging**
