### PR TITLE
Add translation/internationalization

### PR DESCRIPTION
**Pull request by bengolder**
This pull request is a work in progress to add translation capability to the app, using [Flask-Babel](https://pythonhosted.org/Flask-Babel/)

**What's changed?**
- added Flask-Babel to dependencies
- added configuration variables for setting locale

### CODE REVIEW

**Comment by bengolder** [comment]
### Making templates translatable

Flask-Babel [uses Jinjas i18nextension](http://stackoverflow.com/a/9515968/399726) to translate strings. It therefore uses some [standardized functions](http://jinja.pocoo.org/docs/dev/templates/#i18n-in-templates) that are available in the template context.

Examples:

This marks the `'Hello World!'` as a string that may be translated.

``` HTML+Django
{{ _('Hello World!') }}
```

If you want to format variables in a translatable string

``` HTML+Django
{{ _('Hello %(name)s!', name='World') }}
```

If you want to create a translatable string that can be pluralized

``` HTML+Django
{{ ngettext('%(num)d apple', '%(num)d apples', apples|count) }}
```

**Comment by bengolder** [comment]
I'll be adding the [`es_US` (United States Spanish) locale](http://lh.2xlibre.net/locale/es_US/)

**Comment by bengolder** [comment]
### Environmental variable configuration

This workflow presumes that the locale key is set as an environmental variable in `.env`. If the variable is not set, then it will default to `'en_US'`. To view spanish translations, add this line to your `.env` file:

``` bash
BABEL_DEFAULT_LOCALE='es_US'
```

### Translation workflow

Flask-Babel draws on [GNU's `gettext` internationalization module](https://www.gnu.org/software/gettext/) for software written in C. This includes a standard set of functions for creating translations of hardcoded strings in an app.

I've added some commands to the Makefile to facilitate the steps in translation process.
1. Wrap hardcoded strings in the gettext function (using `gettext("Some string")` or `_("Some string")`)
2. Update the [gettext message catalog](https://github.com/codeforamerica/rva-screening/blob/bfc8855a3f5e137c49391e2ec7748c7cb4e2c897/app/messages.pot) to include the new strings that need to be translated, using `make export_translations`
3. Write some translations. The easiest way to do this is by opening `app/translations/es_US/LC_MESSAGES/messages.po` in [Poedit](http://poedit.net/). When you hit `Save`, Poedit automatically creates the corresponding `messages.mo` file.
4. If you edit the `messages.po` file with something besides Poedit, you can manually generate `messages.mo` manually with `make compile_translations`.

**Comment by bengolder** [comment]
### What happens when something hasn't been translated?

Then it will display the existing English text, like this:

screen shot 2015-06-15 at 2 02 54 pm

**Comment by bengolder** [comment]
Yay! This is live and works!

I made a separate heroku app,
[https://demo-screener-es.herokuapp.com/](https://demo-screener-es.herokuapp.com/)

Note that this is identical apart from one environmental variable. It uses the same database.

I also edited `make deploy` to deploy to both remote versions.

**To add the spanish branch so that you can do deployments, run:**

``` bash
    git remote add spanish git@heroku.com:demo-screener-es.git
```

Then, to deploy to the spanish branch, you can use:

``` bash
git push spanish master
```

**Comment by bengolder** [comment]
@mapsam & @esmithayer I've ensured that you both are listed as collaborators on both heroku apps.
Once we merge this branch, if you want to do deployments, be sure to make sure you can access both apps in the Heroku dashboard, and run:

``` bash
git remote add spanish git@heroku.com:demo-screener-es.git
```

**Comment by mapsam** [comment]
Thanks, @bengolder! Really nice work on this.

**Pull request merged**
