### PR TITLE
adds `EXAMPLE` to global template context as shorthand for `app/example_data.py`

### PR DESCRIPTION
**Pull request by bengolder**
This should allow for the easy use of fake data in templates for prototyping without touching any of the backend logic or adding anything to `views.py`. It also allows the faked data to be clearly marked in the template as example data using a big obvious capitalized variable name.

Here's what this would look like in `example_data.py`:

``` python
numbers = [1,4,5,6,7]
```

And here's what it would look like in a template:

``` jinja
      <ul>
        {% for number in EXAMPLE.numbers %}
        <li>{{number}}</li>
        {% endfor %}
      </ul>
```

### CODE REVIEW

**Comment by mapsam** [comment]
Nice! Adding to the global template context means it doesn't have to be passed through the route, yes? Does this also depend on #112 being merged in?

**Comment by bengolder** [comment]
@svmatthews nope, totally independent from the other one, built on top of the current master branch. I was thinking that this might help me make some prototypes for different interface ideas based on the open issues.

**Comment by mapsam** [comment]
Huzzah! Seems great to me. @esmithayer?

**Comment by esmithayer** [comment]
Sounds good. But the idea is still to make new templates for prototyping rather than having "if patient otherwise example data" all over the current templates, right?

**Comment by bengolder** [comment]
Yes

**Comment by mapsam** [comment]
:+1:

**Comment by bengolder** [comment]
Assuming this is okay and that I answered your concerns. Let me know if it's not.

**Pull request merged**
